const createMainContent= (main, greeting="About Us") => {
  const copyGreeting = document.createElement("h2");
  copyGreeting.classList.add("copy-greeting");
  copyGreeting.classList.add("heading");
  copyGreeting.textContent = greeting;

  const copy = document.createElement("p");
  copy.textContent = "Eu scelerisque felis imperdiet proin fermentum leo vel orci. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Semper eget duis at tellus at. Etiam erat velit scelerisque in dictum non consectetur a. Iaculis nunc sed augue lacus viverra vitae. Consectetur a erat nam at lectus urna duis convallis. Felis bibendum ut tristique et. Eget velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Auctor urna nunc id cursus metus aliquam eleifend mi. Justo nec ultrices dui sapien eget. Aliquet risus feugiat in ante metus dictum. Imperdiet proin fermentum leo vel orci porta. Dolor sed viverra ipsum nunc aliquet. Integer malesuada nunc vel risus commodo viverra. A pellentesque sit amet porttitor eget. Tristique et egestas quis ipsum suspendisse. Eu scelerisque felis imperdiet proin fermentum leo vel orci. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Semper eget duis at tellus at. Etiam erat velit scelerisque in dictum non consectetur a. Iaculis nunc sed augue lacus viverra vitae. Consectetur a erat nam at lectus urna duis convallis. Felis bibendum ut tristique et. Eget velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Auctor urna nunc id cursus metus aliquam eleifend mi. Justo nec ultrices dui sapien eget. Aliquet risus feugiat in ante metus dictum. Imperdiet proin fermentum leo vel orci porta. Dolor sed viverra ipsum nunc aliquet. Integer malesuada nunc vel risus commodo viverra. A pellentesque sit amet porttitor eget. Tristique et egestas quis ipsum suspendisse. A cras semper auctor neque vitae. Dignissim sodales ut eu sem integer. Tortor consequat id porta nibh venenatis cras sed felis. Bibendum at varius vel pharetra vel turpis nunc. Malesuada fames ac turpis egestas sed. Diam quam nulla porttitor massa id neque aliquam vestibulum morbi. Purus non enim praesent elementum facilisis leo vel fringilla. Lectus quam id leo in vitae turpis massa sed elementum. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Dolor sed viverra ipsum nunc aliquet bibendum. Ut tortor pretium viverra suspendisse potenti. Quis commodo odio aenean sed adipiscing diam donec adipiscing tristique. Turpis massa tincidunt dui ut ornare lectus sit amet. Cras pulvinar mattis nunc sed blandit libero volutpat sed cras. Sed euismod nisi porta lorem mollis. Posuere ac ut consequat semper viverra nam. Sed id semper risus in hendrerit gravida rutrum. Sit amet mattis vulputate enim nulla aliquet porttitor. Magna fermentum iaculis eu non diam phasellus.";
  main.appendChild(copyGreeting);
  main.appendChild(copy);
}

export default createMainContent;
